# Generated by Django 4.2.23 on 2025-08-08 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, help_text='Opcional - formato: +54 XX XXXX XXXX', max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_proyecto', models.CharField(choices=[('residencial', 'Instalación Residencial'), ('comercial', 'Instalación Comercial'), ('industrial', 'Instalación Industrial'), ('autoconsumo', 'Sistema de Autoconsumo'), ('baterias', 'Sistema con Baterías'), ('mantenimiento', 'Mantenimiento'), ('consultoria', 'Consultoría Energética'), ('otro', 'Otro')], default='residencial', max_length=20, verbose_name='Tipo de proyecto')),
                ('mensaje', models.TextField(help_text='Contanos sobre tu proyecto o consulta', verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas para uso interno del equipo', null=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
