# Generated by Django 4.2.23 on 2025-07-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo del proyecto de instalacion solar', max_length=200, verbose_name='Titulo del Proyecto')),
                ('location', models.CharField(help_text='Provincia, Pais donde se realizo el proyecto', max_length=200, verbose_name='Ubicacion')),
                ('date_completed', models.DateField(help_text='Fecha en que se completo el proyecto', verbose_name='Fecha de Finalizacion')),
                ('description_short', models.CharField(help_text='Resumen breve del proyecto (maximo 300 caracteres)', max_length=300, verbose_name='Descripcion Corta')),
                ('description_full', models.TextField(help_text='Descripcion detallada del proyecto, tecnologia utilizada, beneficios obtenidos', verbose_name='Descripcion Completa')),
                ('featured_image', models.ImageField(help_text='Imagen representativa del proyecto (recomendado: 1200x800px)', upload_to='projects/images/', verbose_name='Imagen Principal')),
                ('power_capacity', models.CharField(blank=True, help_text='Ej: 50kW, 100kW, 2.5MW', max_length=50, verbose_name='Potencia Instalada')),
                ('client_type', models.CharField(blank=True, help_text='Ej: Residencial, Comercial, Industrial', max_length=100, verbose_name='Tipo de Cliente')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar para mostrar en la pagina principal', verbose_name='Proyecto Destacado')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar el proyecto del sitio web', verbose_name='Activo')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automaticamente desde el titulo', max_length=250, unique=True, verbose_name='URL Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-date_completed', '-created_at'],
            },
        ),
    ]
