# Generated by Django 4.2.23 on 2025-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_angulotejado_costoinstalacion_factororientacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePortada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para identificar esta configuración de portada', max_length=100, verbose_name='Nombre de la Portada')),
                ('tipo_multimedia', models.CharField(choices=[('animacion', 'Animación de Electrones'), ('video', 'Video')], default='animacion', help_text='Tipo de contenido a mostrar en la portada', max_length=20, verbose_name='Tipo de Multimedia')),
                ('video_url', models.URLField(blank=True, help_text='URL del video (YouTube, Vimeo, Google Drive, Dropbox, MP4 directo)', null=True, verbose_name='URL del Video')),
                ('video_autoplay', models.BooleanField(default=True, help_text='Reproducir automáticamente al cargar la página', verbose_name='Reproducción Automática')),
                ('video_muted', models.BooleanField(default=True, help_text='Iniciar el video silenciado (recomendado para autoplay)', verbose_name='Silenciado')),
                ('video_show_controls', models.BooleanField(default=False, help_text='Mostrar controles de reproducción del video', verbose_name='Mostrar Controles')),
                ('video_loop', models.BooleanField(default=True, help_text='Repetir el video continuamente', verbose_name='Reproducción en Bucle')),
                ('video_platform', models.CharField(blank=True, help_text='Se detecta automáticamente al guardar', max_length=20, verbose_name='Plataforma de Video')),
                ('video_id', models.CharField(blank=True, help_text='Se extrae automáticamente de la URL', max_length=100, verbose_name='ID del Video')),
                ('video_embed_url', models.URLField(blank=True, help_text='URL generada para insertar el video', verbose_name='URL de Inserción')),
                ('video_thumbnail_url', models.URLField(blank=True, help_text='URL de la imagen de previsualización', verbose_name='URL de Thumbnail')),
                ('activa', models.BooleanField(default=False, help_text='Solo una portada puede estar activa a la vez', verbose_name='Portada Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Portada Principal',
                'verbose_name_plural': 'Configuración de Portada',
                'ordering': ['-activa', '-fecha_actualizacion'],
            },
        ),
    ]
