# Generated by Django 4.2.23 on 2025-08-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homeportada'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeportada',
            name='video_archivo',
            field=models.FileField(blank=True, help_text='Archivo MP4 local para la portada. Prioridad sobre URL si ambos están presentes.', null=True, upload_to='videos/portada/', verbose_name='Archivo MP4'),
        ),
    ]
