# Generated by Django 4.2.23 on 2025-08-12 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion breve de la categoria')),
                ('icono', models.CharField(blank=True, help_text='Clase de icono FontAwesome (ej: fas fa-solar-panel)', max_length=50)),
                ('color', models.CharField(default='#006466', help_text='Color en formato hex (ej: #006466)', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparicion (menor numero = primero)')),
                ('activa', models.BooleanField(default=True, help_text='Si esta marcada, la categoria aparece en el sitio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo de la noticia', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('descripcion_corta', models.TextField(help_text='Resumen que aparece en las tarjetas y como meta descripcion', max_length=300)),
                ('contenido', models.TextField(help_text='Contenido completo del articulo')),
                ('tipo_multimedia', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video de Vimeo'), ('ninguno', 'Sin multimedia')], default='imagen', help_text='Selecciona el tipo de multimedia para el articulo', max_length=10)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal del articulo (JPG, PNG)', null=True, upload_to='noticias/imagenes/')),
                ('video_vimeo_url', models.URLField(blank=True, help_text='URL completa del video de Vimeo (ej: https://vimeo.com/123456789)')),
                ('video_vimeo_id', models.CharField(blank=True, help_text='ID del video de Vimeo (se extrae automaticamente de la URL)', max_length=20)),
                ('autor', models.CharField(default='Equipo INGLAT', max_length=100)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de publicacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('meta_descripcion', models.CharField(blank=True, help_text='Descripcion para motores de busqueda (max 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=200)),
                ('destacada', models.BooleanField(default=False, help_text='Si esta marcada, aparece en la pagina principal')),
                ('activa', models.BooleanField(default=True, help_text='Si esta marcada, la noticia es visible en el sitio')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden manual (menor numero = mas arriba)')),
                ('categoria', models.ForeignKey(help_text='Categoria de la noticia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categoria')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion', 'orden'],
            },
        ),
    ]
