# Generated by Django 4.2.23 on 2025-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='video_autoplay',
            field=models.BooleanField(default=False, help_text='Reproducir automaticamente en la vista detalle'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_embed_url_cached',
            field=models.URLField(blank=True, help_text='URL de embed cacheada (se genera automaticamente)'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_id',
            field=models.CharField(blank=True, help_text='ID del video (se extrae automaticamente)', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_muted',
            field=models.BooleanField(default=True, help_text='Silenciar video por defecto'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_platform',
            field=models.CharField(blank=True, help_text='Plataforma de video (se detecta automaticamente)', max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_show_controls',
            field=models.BooleanField(default=True, help_text='Mostrar controles de video'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_thumbnail_url',
            field=models.URLField(blank=True, help_text='URL de thumbnail del video (se genera automaticamente)'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL publica de video. Soportamos: YouTube, Vimeo, Google Drive, Dropbox y URLs directas MP4. Ejemplo: https://www.youtube.com/watch?v=abc123'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video_vimeo_id',
            field=models.CharField(blank=True, help_text='DEPRECATED: Usar campo video_id. ID del video de Vimeo', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video_vimeo_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Usar campo video_url. URL completa del video de Vimeo'),
        ),
    ]
