# Generated by Django 4.2.23 on 2025-08-13 16:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_noticia_video_autoplay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=tinymce.models.HTMLField(help_text='Contenido completo del articulo con formato rico'),
        ),
    ]
