# Generated by Django 4.2.23 on 2025-08-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_noticia_contenido'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['activa', 'orden'], name='blog_categoria_activa_orden'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['activa', '-fecha_publicacion'], name='blog_noticia_activa_fecha'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['destacada', 'activa'], name='blog_noticia_destacada'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['autor', 'activa'], name='blog_noticia_autor'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['categoria', 'activa', '-fecha_publicacion'], name='blog_noticia_categoria'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['activa', 'categoria', '-fecha_publicacion'], name='blog_noticia_main_query'),
        ),
    ]
