# Generated by Django 4.2.23 on 2025-09-12 16:24

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
        migrations.AddField(
            model_name='noticia',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo multimedia: JPG/PNG para imagenes o MP4/WebM/MOV para videos', null=True, upload_to='noticias/archivos/', validators=[apps.blog.models.validate_multimedia_file]),
        ),
        migrations.AddField(
            model_name='noticia',
            name='thumbnail_custom',
            field=models.ImageField(blank=True, help_text='Miniatura personalizada para mostrar en las tarjetas (opcional)', null=True, upload_to='noticias/thumbnails/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_loop',
            field=models.BooleanField(default=True, help_text='Reproducir video en bucle infinito'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tipo_multimedia',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('ninguno', 'Sin multimedia')], default='imagen', help_text='Selecciona el tipo de multimedia para el articulo', max_length=10),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video_autoplay',
            field=models.BooleanField(default=True, help_text='Reproducir automaticamente en la vista detalle'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL publica de imagen o video. Soportamos: YouTube, Vimeo, Google Drive, Dropbox, URLs directas de imagenes (JPG/PNG) o videos (MP4). Ejemplo: https://www.youtube.com/watch?v=abc123'),
        ),
    ]
