"""
Django settings for INGLAT project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Usar python-decouple para mejor manejo de variables de entorno
try:
    from decouple import config
    def get_env_variable(var_name, default=None):
        if default is not None:
            return config(var_name, default=default)
        return config(var_name)
except ImportError:
    # Fallback a implementación manual si decouple no está disponible
    def get_env_variable(var_name, default=None):
        try:
            return os.environ[var_name]
        except KeyError:
            if default is not None:
                return default
            error_msg = f"Set the {var_name} environment variable"
            raise ImproperlyConfigured(error_msg)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_variable('DEBUG', 'False').lower() in ['true', '1', 'yes', 'on']

ALLOWED_HOSTS = get_env_variable('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'apps.core.apps.CoreConfig',
    'apps.simulador.apps.SimuladorConfig',
    'apps.projects',
    'apps.blog.apps.BlogConfig',
    'apps.contact.apps.ContactConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'INGLAT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'INGLAT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_variable('DB_NAME', 'inglat_db'),
        'USER': get_env_variable('DB_USER', 'postgres'),
        'PASSWORD': get_env_variable('DB_PASSWORD'),
        'HOST': get_env_variable('DB_HOST', 'localhost'),
        'PORT': get_env_variable('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded content)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# APIs de imágenes para EstefaniPUBLI - Configuración segura
try:
    PEXELS_API_KEY = get_env_variable('PEXELS_API_KEY')
    PIXABAY_API_KEY = get_env_variable('PIXABAY_API_KEY')
    
    # Validar que las API keys no están vacías
    if not PEXELS_API_KEY or not PIXABAY_API_KEY:
        if DEBUG:
            print("⚠️  ADVERTENCIA: API keys de imágenes no configuradas completamente")
        else:
            raise ImproperlyConfigured("API keys de Pexels y Pixabay son requeridas para EstefaniPUBLI")
            
except ImproperlyConfigured:
    if DEBUG:
        # En desarrollo, usar claves de desarrollo (ya validadas y seguras)
        PEXELS_API_KEY = get_env_variable('PEXELS_API_KEY', 'fNeW3dU9Vyy4WpU3OaBvxKf8RAZHXgP2nHWpqvIjSLU3wC4fJBVVpa40')
        PIXABAY_API_KEY = get_env_variable('PIXABAY_API_KEY', '51882759-985a415c97f74baf1d84924fe')
        print("🔑 INFO: Usando API keys de desarrollo para EstefaniPUBLI")
    else:
        # En producción, requerir configuración explícita
        raise ImproperlyConfigured("API keys de imágenes son requeridas en producción")

# Configuración de imágenes automáticas - Optimizada para estabilidad
IMAGE_SEARCH_CONFIG = {
    'max_images_per_search': 5,
    'preferred_orientation': 'landscape',
    'min_image_width': 800,
    'min_image_height': 600,
    'timeout_seconds': 60,  # Aumentado de 30 a 60 segundos
    'retry_attempts': 5,    # Aumentado de 3 a 5 intentos
    'connection_timeout': 30,  # Timeout específico para conexión
    'read_timeout': 45,     # Timeout específico para lectura
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration - SpaceMail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = get_env_variable('EMAIL_HOST', 'mail.spacemail.com')
EMAIL_PORT = int(get_env_variable('EMAIL_PORT', '465'))
EMAIL_USE_SSL = get_env_variable('EMAIL_USE_SSL', 'True').lower() == 'true'
EMAIL_USE_TLS = False  # Must be False when using SSL on port 465
EMAIL_HOST_USER = get_env_variable('EMAIL_HOST_USER', 'info@inglat.com')
# Configuración de EMAIL_HOST_PASSWORD con manejo de errores
try:
    EMAIL_HOST_PASSWORD = get_env_variable('EMAIL_HOST_PASSWORD')
except ImproperlyConfigured:
    if DEBUG:
        EMAIL_HOST_PASSWORD = ''
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        print("⚠️  ADVERTENCIA: EMAIL_HOST_PASSWORD no configurado. Usando backend de consola para desarrollo.")
    else:
        raise ImproperlyConfigured("EMAIL_HOST_PASSWORD es requerido en producción")

DEFAULT_FROM_EMAIL = get_env_variable('DEFAULT_FROM_EMAIL', 'info@inglat.com')

# Email Recipients
NOTIFICATION_EMAIL = get_env_variable('NOTIFICATION_EMAIL', 'contacto@inglat.com')

# WhatsApp Configuration
WHATSAPP_NUMBER = get_env_variable('WHATSAPP_NUMBER', '541167214369')
WHATSAPP_DEFAULT_MESSAGE = get_env_variable('WHATSAPP_DEFAULT_MESSAGE', 'Hola, me interesa obtener más información sobre sus servicios.')

# Email Debugging - Configuración adicional para debugging
EMAIL_TIMEOUT = 10  # Reducido de 30s a 10s para mejor rendimiento
EMAIL_USE_LOCALTIME = True

# Logging Configuration for Debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'email_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'email.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.mail': {
            'handlers': ['email_file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'apps.contact': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Security Settings for Production
# Configuración de seguridad mejorada para deploy

# HTTPS Security Headers
SECURE_HSTS_SECONDS = int(get_env_variable('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_env_variable('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True' if not DEBUG else 'False').lower() == 'true'
SECURE_HSTS_PRELOAD = get_env_variable('SECURE_HSTS_PRELOAD', 'True' if not DEBUG else 'False').lower() == 'true'

# SSL/HTTPS Configuration
SECURE_SSL_REDIRECT = get_env_variable('SECURE_SSL_REDIRECT', 'True' if not DEBUG else 'False').lower() == 'true'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None

# Secure Cookies
SESSION_COOKIE_SECURE = get_env_variable('SESSION_COOKIE_SECURE', 'True' if not DEBUG else 'False').lower() == 'true'
CSRF_COOKIE_SECURE = get_env_variable('CSRF_COOKIE_SECURE', 'True' if not DEBUG else 'False').lower() == 'true'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Additional Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'theme': 'silver',
    'height': 500,
    'menubar': True,
    'plugins': 'advlist autolink lists link image charmap print preview anchor '
               'searchreplace visualblocks code fullscreen insertdatetime media '
               'table paste code help wordcount emoticons colorpicker textcolor '
               'fontselect fontsizeselect formatselect',
    'toolbar': 'undo redo | formatselect fontselect fontsizeselect | '
               'bold italic underline strikethrough | forecolor backcolor | '
               'alignleft aligncenter alignright alignjustify | '
               'bullist numlist outdent indent | '
               'link image media table | '
               'code preview fullscreen help',
    'font_formats': 'Arial=arial,helvetica,sans-serif;'
                    'Arial Black=arial black,avant garde;'
                    'Book Antiqua=book antiqua,palatino;'
                    'Comic Sans MS=comic sans ms,sans-serif;'
                    'Courier New=courier new,courier;'
                    'Georgia=georgia,palatino;'
                    'Helvetica=helvetica;'
                    'Impact=impact,chicago;'
                    'Symbol=symbol;'
                    'Tahoma=tahoma,arial,helvetica,sans-serif;'
                    'Terminal=terminal,monaco;'
                    'Times New Roman=times new roman,times;'
                    'Trebuchet MS=trebuchet ms,geneva;'
                    'Verdana=verdana,geneva;'
                    'Webdings=webdings;'
                    'Wingdings=wingdings,zapf dingbats',
    'fontsize_formats': '8pt 10pt 12pt 14pt 18pt 24pt 36pt 48pt 60pt 72pt 96pt',
    'content_style': 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
    'branding': False,
    'language': 'es',
    'relative_urls': False,
    'remove_script_host': False,
    'convert_urls': True,
}
